# permissions for end users to view merestapigoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: merestapigo-viewer-role
rules:
- apiGroups:
  - cache.my.domain
  resources:
  - merestapigoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.my.domain
  resources:
  - merestapigoes/status
  verbs:
  - get
