apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-deployment
  labels:
    app: customers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
       - name: customers
         image: tamim447/test_repo:latest
         ports:
         - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
spec:
  ports:
   - port: 80
     protocol: TCP
     targetPort: 8080
  selector:
    app: customers
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service-nodeport
spec:
  type: NodePort
  selector:
    app: customers
  ports:
   - protocol: TCP
     port: 80
     targetPort: 8080
     nodePort: 30036
