apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    name: mongomatch
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongomatch
  template:
    metadata:
      labels:
        name: mongomatch
    spec:
      volumes:
        - name: volume
          hostPath:
            path: /Users/shahadathhossaintamim/Dropbox/Mac/Desktop/mydb
      containers:
        - image: mongo
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /data/db
              name: volume
          name: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: 'mongoadmin'
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: 'abc123'
