apiVersion: v1
kind: Service
metadata:
  name: mongoservice
  labels:
    app: mongomatch
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: mongomatch
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: 'mongoservice'
  replicas: 1
  selector:
    matchLabels:
      app: mongomatch
  template:
    metadata:
      labels:
        app: mongomatch
    spec:
      containers:
        - image: mongo
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /data/db
              name: myvolume
          name: mongo
          ports:
            - containerPort: 27017
  volumeClaimTemplates:
    - metadata:
        name: myvolume
      spec:
        accessModes: ['ReadWriteOnce']
        storageClassName: 'my-storage-class'
        resources:
          requests:
            storage: 1Gi
