# permissions for end users to view tamims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tamim-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - tamims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - tamims/status
  verbs:
  - get
