# permissions for end users to edit tamims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tamim-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - tamims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - tamims/status
  verbs:
  - get
